"""Pull Request Client: Delivers generated artifacts as a PR to the client's repo.

Instead of deploying directly to Synapse, this creates a branch with all generated
SQL and ADF JSON files, then opens a Pull Request in the client's ADO Git repository.

This fits into the client's existing CI/CD pipeline for review and deployment.
"""

from __future__ import annotations

import base64
import json
import logging
import os
from typing import Optional

import requests

from .config import AppConfig

logger = logging.getLogger(__name__)

ADO_API_VERSION = "7.1"


class PRClient:
    """Creates Pull Requests in Azure DevOps with generated artifacts."""

    def __init__(self, config: AppConfig):
        self._org = config.ado_org
        self._project = config.ado_project
        self._repo = config.ado_repo
        self._pat = os.environ.get("ADO_PAT", "")
        self._base_url = (
            f"https://dev.azure.com/{self._org}/{self._project}"
            f"/_apis/git/repositories/{self._repo}"
        )
        self._headers = {
            "Authorization": f"Basic {base64.b64encode(f':{self._pat}'.encode()).decode()}",
            "Content-Type": "application/json",
        }

    def create_pr(
        self,
        story_id: str,
        title: str,
        artifacts: list[dict],
        target_branch: str = "develop",
        base_path: str = "generated",
        description: str = "",
    ) -> dict:
        """Create a branch with artifacts and open a PR.

        Args:
            story_id: Story identifier (used for branch name)
            title: PR title
            artifacts: List of dicts with keys: file_name, content, layer
            target_branch: Branch to merge into
            base_path: Root folder for generated files
            description: PR description

        Returns:
            Dict with pr_id, pr_url, branch_name, file_count
        """
        if not self._pat or not self._org:
            return {"status": "skipped", "reason": "ADO not configured"}

        branch_name = f"feature/auto-{story_id.lower().replace(' ', '-')}"
        ref_name = f"refs/heads/{branch_name}"
        target_ref = f"refs/heads/{target_branch}"

        logger.info("Creating PR for %s: %d artifacts -> %s", story_id, len(artifacts), target_branch)

        try:
            # 1. Get the latest commit on target branch
            refs_resp = requests.get(
                f"{self._base_url}/refs?filter=heads/{target_branch}&api-version={ADO_API_VERSION}",
                headers=self._headers, timeout=15,
            )
            refs_resp.raise_for_status()
            refs = refs_resp.json().get("value", [])
            if not refs:
                return {"status": "error", "reason": f"Branch '{target_branch}' not found"}
            base_commit = refs[0]["objectId"]

            # 2. Build the push with all artifacts as file changes
            changes = []
            for art in artifacts:
                layer = art.get("layer", "")
                file_name = art.get("file_name", art.get("object_name", "unknown.sql"))
                content = art.get("content", "")

                # Organize by layer
                if layer:
                    path = f"/{base_path}/{story_id}/{layer}/{file_name}"
                else:
                    path = f"/{base_path}/{story_id}/{file_name}"

                changes.append({
                    "changeType": "add",
                    "item": {"path": path},
                    "newContent": {
                        "content": content,
                        "contentType": "rawtext",
                    },
                })

            # Add a summary README
            readme_lines = [
                f"# Auto-Generated: {story_id}",
                f"",
                f"**Title:** {title}",
                f"**Generated by:** BI Automation Platform",
                f"**Artifacts:** {len(artifacts)} files",
                f"",
                f"## Files",
            ]
            for art in artifacts:
                layer = art.get("layer", "")
                fname = art.get("file_name", art.get("object_name", ""))
                atype = art.get("artifact_type", "")
                readme_lines.append(f"- `{layer}/{fname}` ({atype})")
            readme_lines.extend(["", "## Review Checklist", "- [ ] SQL syntax verified",
                                 "- [ ] Naming conventions match", "- [ ] Business logic correct",
                                 "- [ ] No breaking changes to existing objects"])

            changes.append({
                "changeType": "add",
                "item": {"path": f"/{base_path}/{story_id}/README.md"},
                "newContent": {"content": "\n".join(readme_lines), "contentType": "rawtext"},
            })

            # 3. Push to new branch
            push_body = {
                "refUpdates": [{"name": ref_name, "oldObjectId": "0" * 40}],
                "commits": [{
                    "comment": f"[Auto] Generated artifacts for {story_id}\n\n{title}",
                    "changes": changes,
                }],
            }
            push_resp = requests.post(
                f"{self._base_url}/pushes?api-version={ADO_API_VERSION}",
                headers=self._headers, json=push_body, timeout=30,
            )
            push_resp.raise_for_status()

            # 4. Create Pull Request
            pr_body = {
                "sourceRefName": ref_name,
                "targetRefName": target_ref,
                "title": f"[Auto] {title} ({story_id})",
                "description": description or self._build_pr_description(story_id, title, artifacts),
                "isDraft": False,
            }
            pr_resp = requests.post(
                f"{self._base_url}/pullrequests?api-version={ADO_API_VERSION}",
                headers=self._headers, json=pr_body, timeout=15,
            )
            pr_resp.raise_for_status()
            pr_data = pr_resp.json()

            pr_id = pr_data.get("pullRequestId", 0)
            pr_url = f"https://dev.azure.com/{self._org}/{self._project}/_git/{self._repo}/pullrequest/{pr_id}"

            logger.info("PR created: #%d -> %s", pr_id, pr_url)
            return {
                "status": "created",
                "pr_id": pr_id,
                "pr_url": pr_url,
                "branch_name": branch_name,
                "file_count": len(artifacts) + 1,
            }

        except requests.HTTPError as e:
            error_detail = ""
            try:
                error_detail = e.response.json().get("message", "")[:300]
            except Exception as parse_err:
                logger.debug("Non-critical error parsing HTTP error response: %s", parse_err)
                error_detail = str(e)[:300]
            logger.error("PR creation failed: %s", error_detail)
            return {"status": "error", "reason": error_detail}
        except Exception as e:
            logger.error("PR creation failed: %s", str(e)[:300])
            return {"status": "error", "reason": str(e)[:300]}

    def _build_pr_description(self, story_id: str, title: str, artifacts: list[dict]) -> str:
        """Build a rich PR description with artifact details."""
        layers = {}
        for art in artifacts:
            layer = art.get("layer", "other")
            if layer not in layers:
                layers[layer] = []
            layers[layer].append(art.get("object_name", art.get("file_name", "")))

        lines = [
            f"## Auto-Generated by BI Automation Platform",
            f"",
            f"**Story:** {story_id}",
            f"**Title:** {title}",
            f"**Total artifacts:** {len(artifacts)}",
            f"",
        ]
        for layer, objects in layers.items():
            lines.append(f"### {layer.title()} Layer ({len(objects)} objects)")
            for obj in objects:
                lines.append(f"- `{obj}`")
            lines.append("")

        lines.extend([
            "---",
            "*This PR was automatically generated. Please review the SQL before merging.*",
        ])
        return "\n".join(lines)
